all: simple_gamble.png, utility.png, change_in_utility.png

simple_gamble.png:
	make --always-make simple_gamble.pdf -C ../figure/
	cp ../figure/simple_gamble.png simple_gamble.png

change_in_utility.png:
	make --always-make change_in_utility.pdf -C ../figure/
	cp ../figure/change_in_utility.png change_in_utility.png

utility.png:
	make --always-make utility.pdf -C ../figure/
	cp ../figure/utility.png utility.png

